# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python base image
FROM python:3.13-slim-bookworm

# Set the working directory
WORKDIR /app

# Copy the project files to the working directory
COPY . .

# Install the project dependencies using uv
RUN pip install --no-cache-dir uv && uv sync --frozen --no-dev --no-editable

# Expose any necessary ports (if applicable)
# EXPOSE 1234

# Set the environment variables for the location of the snapshot.json if needed
# ENV SNAPSHOT_JSON_PATH=/path/to/snapshot.json

# Define the command to run the server
ENTRYPOINT ["tuyad"]
